import { type ModelInfo, n } from "./model/info.ts";

// All copy in one place (English first; Spanish later is a translation of this file).
// Plain words first, the standard term beside them (section 4.2).

export const S = {
  title: "Rewire",
  orientation: "Qwen3-0.6B, a small open chat AI that runs on your device. Tap any part to see or change it.",
  tinyOrientation: "The tiny model you just trained, running on your device. Type the start of a sentence; tap any part to see or change it.",
  replay: "Replay",
  live: "Live",
  replayHint: "These are recordings of real runs on this model.",
  liveHint: "The model is running on this device.",
  howItWorks: "How it works",
  whatsReal: "What's real here",
  whatsRealBody: [
    "Live: you can run Qwen3-0.6B on this device in its 4-bit form. Guided examples also use recordings from the same model. Nothing you type leaves the device.",
    "Replay: the numbers were computed by the same 4-bit model on another computer and recorded. None of them is illustrative.",
    "Lighting shows each part's direct push toward a word, holding the final normalization's scale fixed. Parts that work through later floors can stay pale.",
    "The live model stores its weights in 4 bits, so it is somewhat weaker than the original 16-bit Qwen3-0.6B: on everyday replies it ranks the same word first 84% of the time, its perplexity on Wikipedia text is 8% higher, and it still knows 97% of the facts the original knows.",
    "A changed model can say false or offensive things. Every changed reply names its changes.",
  ],

  // device check and download (section 5.1)
  checking: "Checking whether this device can run the model…",
  noWebgpu: "This browser can't run the model, so these are recordings of real runs. Browsers with WebGPU, such as recent Chrome, Edge and Safari, can run it live.",
  slow: "This device is too slow to run it live, so these are recordings of real runs.",
  crashed: "The model stopped this tab last time, so these are recordings of real runs.",
  tryAnyway: "Run it live anyway",
  offer: (mb: number | null) => `This device can run the model live. ${mb ? `It is a ${mb} MB download` : "It is a download of a few hundred MB"}. The browser will try to keep it for next time.`,
  download: "Enable live chat",
  downloading: (got: number, total: number) => `Getting the model onto your device: ${total ? `${got} of ${total} MB` : `${got} MB`}.`,
  pause: "Pause",
  resume: "Resume",
  loadingModel: "Starting the model…",
  ready: "The model is running on this device.",
  storageRefused: "This browser would not keep the model, so it will download again next visit.",
  recovering: "The GPU was reset; the model is reloading. Recordings still play.",
  recovered: "The model is ready again. You can continue your reply.",
  retry: "Try again",
  loadError: (m: string) => `The model could not start: ${m}. Recordings still play.`,

  // conversation
  you: "You",
  normal: "Normal",
  changed: "Changed",
  changedBy: (what: string) => `Changed: ${what}`,
  writtenUnder: (what: string) => `Written under: ${what}`,
  cont: "Continue",
  send: "Send",
  placeholderLive: "Ask anything…",
  placeholderTiny: "Start a sentence for it to continue",
  placeholderReplay: "Typing needs the model on this device. Pick a recorded question:",
  whatItReads: "What the model actually reads",
  hideReads: "Hide",
  readsNote: "Everything the model reads, as word pieces (tokens): the start marker, the short system prompt, the markers around each turn and the empty thinking block.",
  thinkingOff: "Thinking is off: the reply starts after an empty thinking block.",
  youPicked: "You picked this word",
  undo: "Undo",
  stopped: (n: number, piece: string) => `Stopped at ${n} ${piece}s.`,
  sameWords: (word: string, a: number, b: number) =>
    b < a ? `Same words, less sure: "${word}" fell from ${a}% to ${b}%.` : `Same words, more sure: "${word}" rose from ${a}% to ${b}%.`,
  sameNumbers: "Same words and nearly the same probabilities: this change barely matters for this reply.",
  underlineNote: "Underlined: words the changed model finds unlikely.",
  reply: "Reply",
  replyWords: "Arrow keys move between word pieces; Enter shows what went into one.",
  notRecorded: "This change wasn't recorded for this question. It runs live once the model is on this device.",
  contextFull: "This conversation has reached the model's context limit here.",
  freshStart: "Start fresh",

  // chips
  resetAll: "Reset all",
  remove: (what: string) => `Remove: ${what}`,
  chip: {
    head: (f: number, h: number, m: string) => `Head ${h} on floor ${f} ${m}`,
    memory: (f: number, m: string) => `Memory block on floor ${f} ${m}`,
    floor: (f: number, m: string) => `Floor ${f} ${m}`,
    swap: (a: string, b: string) => `${a} and ${b} swapped`,
    hidden: (w: string) => `"${w}" hidden from later words`,
    concept: (c: string, f: number, s: number) => `"${c}" pushed at floor ${f}, strength ${s}`,
    bits: (b: number) => `${b} bits`,
    zeroed: (f: number, n: number) => (n === 1 ? `one weight on floor ${f} set to zero` : `${n} weights on floor ${f} set to zero`),
  },
  mult: (m: number) => (m === 0 ? "off" : m === -1 ? "flipped" : m === 1 ? "normal" : `×${m}`),

  // knob stops (section 4.3)
  stops: [
    { v: -1, label: "Flip" },
    { v: 0, label: "Off" },
    { v: 1, label: "Normal" },
    { v: 2, label: "×2" },
    { v: 5, label: "×5" },
  ],

  // tower
  tower: "The tower",
  towerFor: (w: string) => `Pushes toward "${w}"`,
  towerNone: "Tap a word in a reply to light up the parts that pushed toward it.",
  viewPush: "Push",
  viewDiff: "Difference",
  diffNote: "Changed model minus normal model, on the normal reply's words.",
  diffNone: "The Difference view needs a change.",
  towerCaption: (m: ModelInfo) => "Lighting shows each part's direct push only; parts that work through later floors can stay pale." +
    (m.id === "tiny" ? "" : " The first floor barely lights, yet losing it is fatal."),
  wordsIn: "Words in",
  wordsOut: "Words out",
  floorN: (n: number) => `Floor ${n}`,
  headN: (n: number) => `Head ${n}`,
  memoryBlock: "Memory block",
  bitsLabel: (b: number) => `${b} bits`,
  summary: (a: number, b: number, w: string) => `Floors ${a} to ${b} push hardest toward "${w}".`,
  pushTo: (v: number, w: string) => `${v >= 0 ? "+" : "−"}${Math.abs(v).toFixed(2)} toward "${w}"`,

  // detail panel parts
  what: "What it is",
  numbers: "Its numbers",
  control: "Its control",
  terms: {
    token: ["Word piece", "token"],
    embedding: ["Dictionary", "embedding matrix"],
    residual: ["Stream", "residual stream"],
    layer: ["Floor", "layer (transformer block)"],
    head: ["Head", "attention head"],
    attention: ["Attention line", "attention weight"],
    induction: ["Copying head", "induction head"],
    mlp: ["Memory block", "MLP (feed-forward network)"],
    neuron: ["Unit", "MLP neuron"],
    lens: ["Floor guess", "logit lens"],
    steering: ["Concept", "steering vector"],
  } as Record<string, [string, string]>,
  def: (m: ModelInfo) => ({
    word: `A ${m.piece} the model wrote. It was drawn from the candidates below.`,
    token: m.id === "tiny" ? "The tiny model reads one letter at a time; its dictionary has 97 of them."
      : "Text is cut into word pieces before the model reads it. This model knows 151,669 of them.",
    dictionary: `Each ${m.piece} has a row of ${n(m.width)} numbers in the dictionary. The same table turns numbers back into ${m.piece}s at the end.`,
    stream: `${n(m.width)} numbers per ${m.piece} that every floor reads and adds to.`,
    floor: `One of ${m.floors} floors. Each reads the stream, runs ${m.heads} heads and a memory block, and adds their results back.`,
    head: `One of ${m.heads} heads on this floor. It looks back at earlier ${m.piece}s and brings some of their numbers forward. Pairs of heads share their keys and values.`,
    memory: `One per floor, with ${n(m.units)} units. It transforms each ${m.piece}'s numbers on its own. Studies find stored associations here, but where facts live is still debated.`,
    unit: `One of the ${n(m.units)} units in a memory block.`,
    lens: "What the model would say if it stopped at that floor. Guesses on early floors are unreliable.",
    concept: "A direction in the stream, found from example sentences. Adding it pushes every later word toward the concept.",
    out: `The final normalization, then a score for every one of the ${n(m.vocab)} ${m.piece}s, the probabilities, and the choice.`,
    bits: "Each weight inside the floors is stored with 4 bits: 16 possible values in each group of 32 weights. Fewer bits means coarser numbers. This control leaves the dictionary as it is.",
    temperature: "How the next word is picked, not the model. Scores are divided by the temperature: higher means more surprising picks.",
    push: `Its direct push toward the chosen ${m.piece}: its output, scaled by the final normalization, dotted with the ${m.piece}'s dictionary row minus the average row.`,
    position: "Position enters by rotating queries and keys, not by adding a vector.",
  }),

  candidates: "Candidates",
  candidatesNote: (k: number) => `The draw used the top ${k} after the cut (top-p 0.8).`,
  cut: "cut",
  forcePick: "Use this word",
  floorGuesses: "Floor guesses",
  guessesNote: "Guesses on early floors are unreliable.",
  dictionaryRow: (id: number) => `Dictionary row ${id}`,
  swapWith: "Swap with another word",
  swapSuggest: "Suggested pairs",
  swapNotSingle: "This word is several pieces, so it can't be swapped as a whole.",
  hideWord: "Hide this word from later words",
  unhideWord: "Show this word again",
  pushConcept: "Push a concept here",
  strength: "Strength",
  breakingLine: "breaking line",
  breakingEstimate: "estimated on this floor",
  temperatureLabel: "Temperature",
  temperatureNote: "The model's own numbers stay the same; only the pick changes.",
  noDetail: "Full floor detail is recorded for the words with a dotted underline. Live, every word has it.",
  inspecting: "Computing every step for this word…",
  goToUnit: "Go to unit",
  topUnitsPush: "Units pushing hardest toward the word",
  topUnitsActive: "Most active units",
  attentionLines: "Where it looks",
  attentionMap: "Full attention map",
  zeroBased: (n: number) => `index ${n} in code`,
  foundByTesting: "found by testing",

  // path (section 4.4)
  stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
  next: "Next",
  back: "Back",
  tryOwn: "Try it on your own question",
  tryOwnReplay: "Try it on another question",
  pathTitle: "How it works",
  pathIntro: "Short steps from the dictionary at the bottom to the output at the top, ending with training.",
  close: "Close",
  core: "core",

  // tiny model (section 4.5)
  tiny: {
    title: "Teach a tiny model your writing",
    intro: "A model with the same design as Qwen3-0.6B, about 750 times smaller, learns to imitate a text in front of you. It reads letters instead of word pieces.",
    paste: "Or paste some of your own writing (it stays on this device)",
    builtIn: "Pick a built-in text",
    teach: "Teach",
    stop: "Stop",
    loss: "Loss",
    step: (n: number) => `Step ${n}`,
    sample: "What it writes now",
    slowMotion: "Slow motion: one training step",
    slowIntro: "The probability it gave the right next letter, then the same example after one step.",
    before: "Before the step",
    after: "After the step",
    showMath: "Show the math",
    open: "Open the tiny model",
    back: "Back to Qwen3-0.6B",
    why: "Why not the big one: training all 596 million numbers needs about 9.5 GB for the weights, their gradients and Adam's two running averages. The tiny model learns the same way.",
    recorded: "This device can't train it live, so this is a recorded training run.",
  },

  // accessibility
  skip: "Skip to the conversation",
};
